MCU = STM32F401
BOARD = BLACKPILL_STM32_F401
BOOTLOADER = stm32-dfu

VIA_ENABLE = yes
LTO_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes

MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
